/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import javax.swing.JOptionPane;
import my.models.Medicine;
import my.models.userevents.SubFrameModelAddListener;

/**
 *
 * @author samue
 */
public class MedicineWindow extends javax.swing.JFrame {

   private SubFrameModelAddListener listener;
   private Medicine medicine;
   /**
    * Creates new form MedicineWindow
    */
   public MedicineWindow(Medicine medicine) {
      initComponents();
      this.medicine = medicine;
      this.MedicineNameJTextField.setText(this.medicine.getSearchString());
      this.AvailableStockJTextField.setText(String.valueOf(this.medicine.StockLeft()));
      this.DescriptionJTextArea.setText(this.medicine.getDescription());
      this.OnOrderCheckBox.setSelected(this.medicine.isOnOrder());
      this.setVisible(true);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      MedicineNameJTextField = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      AvailableStockJTextField = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      DescriptionJTextArea = new javax.swing.JTextArea();
      SaveChangesJButton = new javax.swing.JButton();
      OnOrderCheckBox = new javax.swing.JCheckBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setText("Medicine Name");

      MedicineNameJTextField.setEditable(false);

      jLabel2.setText("Available Stock");

      AvailableStockJTextField.addCaretListener(new javax.swing.event.CaretListener() {
         public void caretUpdate(javax.swing.event.CaretEvent evt) {
            AvailableStockJTextFieldCaretUpdate(evt);
         }
      });

      jLabel6.setText("Description");

      DescriptionJTextArea.setColumns(20);
      DescriptionJTextArea.setLineWrap(true);
      DescriptionJTextArea.setRows(5);
      jScrollPane1.setViewportView(DescriptionJTextArea);

      SaveChangesJButton.setText("Save");
      SaveChangesJButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            SaveChangesJButtonMouseClicked(evt);
         }
      });

      OnOrderCheckBox.setText("On Order");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(OnOrderCheckBox)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(SaveChangesJButton)
                  .addGap(29, 29, 29))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addComponent(jLabel3)
                           .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(MedicineNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                           .addComponent(AvailableStockJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jScrollPane1))))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(MedicineNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(AvailableStockJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel6)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(73, 73, 73)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(SaveChangesJButton)
               .addComponent(OnOrderCheckBox))
            .addContainerGap(291, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void AvailableStockJTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_AvailableStockJTextFieldCaretUpdate
      //if(!AvailableStockJTextField.getText().equals("") )
      //{
      // this.medicine.addStock(Integer.parseInt(AvailableStockJTextField.getText()));
     // }
     
   }//GEN-LAST:event_AvailableStockJTextFieldCaretUpdate

   private void SaveChangesJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveChangesJButtonMouseClicked
      if(!AvailableStockJTextField.getText().isEmpty())
      {
         int currentstock = this.medicine.StockLeft();
         int AddedStock = Integer.parseInt(AvailableStockJTextField.getText()) - currentstock;
         this.medicine.addStock(AddedStock);
      }
      if(!DescriptionJTextArea.getText().isEmpty())
      {
         this.medicine.setDescription(DescriptionJTextArea.getText());
      }
      this.medicine.putOnOrder(OnOrderCheckBox.isSelected());
      this.medicine.saveMedicine();
      JOptionPane.showMessageDialog(null, "Your changes have been saved", "Saved Changes", JOptionPane.INFORMATION_MESSAGE);
      
      if(listener != null)
      {
         listener.onSubFrameNewModel(this.medicine);
      }
      
      this.dispose();
   }//GEN-LAST:event_SaveChangesJButtonMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MedicineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MedicineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MedicineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MedicineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            //new MedicineWindow().setVisible(true);
         }
      });
   }

   public void SubFrameModelAddListener (SubFrameModelAddListener listener) {
    this.listener = listener;
   }
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField AvailableStockJTextField;
   private javax.swing.JTextArea DescriptionJTextArea;
   private javax.swing.JTextField MedicineNameJTextField;
   private javax.swing.JCheckBox OnOrderCheckBox;
   private javax.swing.JButton SaveChangesJButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
