/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import my.models.AccountActionRequest;
import my.models.Patient;
import my.models.Secretary;
import my.models.User;
import my.models.User.AccountStatus;
import my.models.userevents.Listable.ListableDirectory;
import my.models.userevents.SubFrameCloseListener;

/**
 *
 * @author samue
 */
public class AccountActionWindow extends javax.swing.JFrame {

   private AccountActionRequest actionRequest;
   private Patient patient;
   private Secretary secretary;
   SubFrameCloseListener listener;
   /**
    * Creates new form AccountActionWindow
    */
   public AccountActionWindow(AccountActionRequest actionRequest, Secretary secretary) {
      initComponents();
      this.actionRequest = actionRequest;
      this.patient = (Patient)User.loadUser(this.actionRequest.getPatientUID());
      this.secretary = secretary;
      this.ConfirmationJTextBox.setSelected(false);
      saveChangesJButton.setEnabled(false);
      switch (patient.getAccountStatus()) {
         case ACTIVE:
            ActiveJRadioButton.setSelected(true);
            break;
         case PENDING:
            PendingJRadioButton.setSelected(true);
            break; 
         default:
            DeletedJRadioButton.setSelected(true);
            break;
      }
      this.setVisible(true);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      saveChangesJButton = new javax.swing.JButton();
      ConfirmationJTextBox = new javax.swing.JCheckBox();
      PendingJRadioButton = new javax.swing.JRadioButton();
      ActiveJRadioButton = new javax.swing.JRadioButton();
      DeletedJRadioButton = new javax.swing.JRadioButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      saveChangesJButton.setText("Save");
      saveChangesJButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveChangesJButtonActionPerformed(evt);
         }
      });

      ConfirmationJTextBox.setText("I confirm my choice");
      ConfirmationJTextBox.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            ConfirmationJTextBoxItemStateChanged(evt);
         }
      });

      buttonGroup1.add(PendingJRadioButton);
      PendingJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      PendingJRadioButton.setText("Pending");

      buttonGroup1.add(ActiveJRadioButton);
      ActiveJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      ActiveJRadioButton.setText("Active");

      buttonGroup1.add(DeletedJRadioButton);
      DeletedJRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      DeletedJRadioButton.setText("Deleted");

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel1.setText("Set New Account Status");

      jLabel2.setText("The users current account status has been selected");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(205, Short.MAX_VALUE)
            .addComponent(ConfirmationJTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(saveChangesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(39, 39, 39))
         .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addGroup(layout.createSequentialGroup()
                  .addGap(10, 10, 10)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(DeletedJRadioButton)
                     .addComponent(ActiveJRadioButton)
                     .addComponent(PendingJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel2))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(97, 97, 97)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(PendingJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ActiveJRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(DeletedJRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(saveChangesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(ConfirmationJTextBox))
            .addGap(24, 24, 24))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   public void SubFrameCloseListener (SubFrameCloseListener listener) {
    this.listener = listener;
}
   
   private void saveChangesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesJButtonActionPerformed
      if(ConfirmationJTextBox.isSelected())
      {
         AccountStatus changeto = AccountStatus.PENDING;
         if(buttonGroup1.getSelection() == ActiveJRadioButton.getModel())
         {
            changeto = AccountStatus.ACTIVE;
         }
         else if(buttonGroup1.getSelection() == PendingJRadioButton.getModel())
         {
            changeto = AccountStatus.PENDING;
         }
         else if(buttonGroup1.getSelection() == DeletedJRadioButton.getModel())
         {
            changeto = AccountStatus.DELETED;
         }
         this.patient.updateAccountStatus(changeto);
         this.patient.saveUser();
         ListableDirectory actionDirectory = new ListableDirectory.ListableTemplateBuilder().AddTopLevelFolder("users").AddFolderUID(this.secretary.getUID()).AddSubFolder("accountactions").Build();
         File file = new File(actionDirectory.GetDirectory()+this.actionRequest.getUID().toString()+".ser");
         file.delete();
         JOptionPane.showMessageDialog(null, "You have changed the account status of an account", "Account Update Changes Saved", JOptionPane.INFORMATION_MESSAGE);
         listener.onSubFrameClose(this);
      }
   }//GEN-LAST:event_saveChangesJButtonActionPerformed

   private void ConfirmationJTextBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ConfirmationJTextBoxItemStateChanged
      saveChangesJButton.setEnabled(ConfirmationJTextBox.isSelected());
   }//GEN-LAST:event_ConfirmationJTextBoxItemStateChanged

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AccountActionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AccountActionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AccountActionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AccountActionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            //new AccountActionWindow().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JRadioButton ActiveJRadioButton;
   private javax.swing.JCheckBox ConfirmationJTextBox;
   private javax.swing.JRadioButton DeletedJRadioButton;
   private javax.swing.JRadioButton PendingJRadioButton;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JButton saveChangesJButton;
   // End of variables declaration//GEN-END:variables
}
