/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import java.awt.Color;
import javax.swing.JOptionPane;
import my.models.*;

public class AdminHomeWindow extends javax.swing.JFrame {
   
   private final Admin WindowAdmin; 
   
   public boolean getUserStatus()
   {
      if(this.WindowAdmin == null)
      {
         return false;
      }
      else
      {
         return true;
      }
   }
   
   public AdminHomeWindow(String UID, String Password) {
      initComponents();
      boolean LoggedIn = false;
      Admin admin = (Admin) User.loadUser(UID);
      if(admin != null)
      {
        if(admin.verifyPassword(Password) == true && admin.getAccountStatus() == User.AccountStatus.ACTIVE)
        {
           LoggedIn = true;
        }
      }
      
      if(LoggedIn == true)
      {
         this.WindowAdmin = (Admin) User.loadUser(UID);
         this.setVisible(LoggedIn);
      }
      else
      {
         this.WindowAdmin = null;
      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      jPanel2 = new javax.swing.JPanel();
      Register_FullName_JTextField = new javax.swing.JTextField();
      Register_Password_JTextField = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      Register_Address_JTextArea = new javax.swing.JTextArea();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      Register_Registerbtn_JButton = new javax.swing.JButton();
      Register_RegisterUID_JLabel = new javax.swing.JLabel();
      Register_TypeDoctor_JRadioBtn = new javax.swing.JRadioButton();
      Register_TypeSecretary_JRadioBtn = new javax.swing.JRadioButton();
      jLabel6 = new javax.swing.JLabel();
      RegisteredUser_UID_JTextField = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

      Register_FullName_JTextField.addCaretListener(new javax.swing.event.CaretListener() {
         public void caretUpdate(javax.swing.event.CaretEvent evt) {
            Register_FullName_JTextFieldCaretUpdate(evt);
         }
      });

      Register_Password_JTextField.addCaretListener(new javax.swing.event.CaretListener() {
         public void caretUpdate(javax.swing.event.CaretEvent evt) {
            Register_Password_JTextFieldCaretUpdate(evt);
         }
      });

      Register_Address_JTextArea.setColumns(20);
      Register_Address_JTextArea.setLineWrap(true);
      Register_Address_JTextArea.setRows(5);
      Register_Address_JTextArea.addCaretListener(new javax.swing.event.CaretListener() {
         public void caretUpdate(javax.swing.event.CaretEvent evt) {
            Register_Address_JTextAreaCaretUpdate(evt);
         }
      });
      jScrollPane1.setViewportView(Register_Address_JTextArea);

      jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel3.setText("Full Name");

      jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel4.setText("Password");

      jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel5.setText("Address");

      Register_Registerbtn_JButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      Register_Registerbtn_JButton.setText("Register");
      Register_Registerbtn_JButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            Register_Registerbtn_JButtonActionPerformed(evt);
         }
      });

      buttonGroup1.add(Register_TypeDoctor_JRadioBtn);
      Register_TypeDoctor_JRadioBtn.setText("Doctor");
      Register_TypeDoctor_JRadioBtn.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            Register_TypeDoctor_JRadioBtnStateChanged(evt);
         }
      });

      buttonGroup1.add(Register_TypeSecretary_JRadioBtn);
      Register_TypeSecretary_JRadioBtn.setText("Secretary");

      jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel6.setText("Profession");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(36, 36, 36)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel6)
                     .addComponent(Register_TypeDoctor_JRadioBtn))
                  .addGap(31, 31, 31)
                  .addComponent(Register_TypeSecretary_JRadioBtn))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(31, 31, 31)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5)
                     .addComponent(jLabel4)
                     .addComponent(jLabel3)
                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addComponent(Register_Password_JTextField)
                        .addComponent(Register_FullName_JTextField))))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(RegisteredUser_UID_JTextField)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(Register_RegisterUID_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(96, 96, 96)
                  .addComponent(Register_Registerbtn_JButton)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(61, 61, 61)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Register_FullName_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(15, 15, 15)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Register_Password_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(Register_TypeDoctor_JRadioBtn)
                     .addComponent(Register_TypeSecretary_JRadioBtn))
                  .addGap(18, 18, 18)
                  .addComponent(Register_Registerbtn_JButton)
                  .addGap(27, 27, 27)
                  .addComponent(Register_RegisterUID_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(RegisteredUser_UID_JTextField))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 522, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void Register_FullName_JTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Register_FullName_JTextFieldCaretUpdate
      if(Register_FullName_JTextField.getText().length() > 6)
      {
         Register_FullName_JTextField.setForeground(Color.GREEN);
         Register_Password_JTextField.setEditable(true);
      }
      else
      {
         Register_FullName_JTextField.setForeground(Color.RED);
         Register_Registerbtn_JButton.setEnabled(false);
      }
   }//GEN-LAST:event_Register_FullName_JTextFieldCaretUpdate

   private void Register_Password_JTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Register_Password_JTextFieldCaretUpdate
      if(Register_Password_JTextField.getText().length() > 6)
      {
         Register_Password_JTextField.setForeground(Color.GREEN);
         Register_Address_JTextArea.setEditable(true);
      }
      else
      {
         Register_Password_JTextField.setForeground(Color.RED);
         Register_Address_JTextArea.setEditable(false);
      }
   }//GEN-LAST:event_Register_Password_JTextFieldCaretUpdate

   private void Register_Address_JTextAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Register_Address_JTextAreaCaretUpdate
      if(Register_Address_JTextArea.getText().length() > 6)
      {
         Register_Address_JTextArea.setForeground(Color.GREEN);
         Register_TypeDoctor_JRadioBtn.setEnabled(true);
         Register_TypeSecretary_JRadioBtn.setEnabled(true);
      }
      else
      {
         Register_Address_JTextArea.setForeground(Color.RED);
         Register_TypeDoctor_JRadioBtn.setEnabled(true);
         Register_TypeSecretary_JRadioBtn.setEnabled(true);
      }
   }//GEN-LAST:event_Register_Address_JTextAreaCaretUpdate

   private void Register_Registerbtn_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_Registerbtn_JButtonActionPerformed
      User newEmployee;
      if(Register_TypeDoctor_JRadioBtn.isSelected())
      {
         newEmployee = new Doctor(User.UIDGenerator('D'));
      }
      else
      {
         newEmployee = new Secretary(User.UIDGenerator('S'));
      }
      
      newEmployee.setAddress(Register_Address_JTextArea.getText());
      newEmployee.setName(Register_FullName_JTextField.getText());
      newEmployee.setPassword(Register_Password_JTextField.getText());
      newEmployee.updateAccountStatus(User.AccountStatus.ACTIVE);
      newEmployee.saveUser();
      JOptionPane.showMessageDialog(null, "The new employee has been created.", "New Employee Created", JOptionPane.INFORMATION_MESSAGE);
      RegisteredUser_UID_JTextField.setText("Here is the employees ID. Don't forget it! " + newEmployee.getUID());
      Register_FullName_JTextField.setText("");
      Register_Password_JTextField.setText("");
      Register_Address_JTextArea.setText("");
      Register_TypeDoctor_JRadioBtn.setEnabled(false);
      Register_TypeSecretary_JRadioBtn.setEnabled(false);
      buttonGroup1.clearSelection();
   }//GEN-LAST:event_Register_Registerbtn_JButtonActionPerformed

   private void Register_TypeDoctor_JRadioBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Register_TypeDoctor_JRadioBtnStateChanged
      Register_Registerbtn_JButton.setEnabled(true);
   }//GEN-LAST:event_Register_TypeDoctor_JRadioBtnStateChanged

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdminHomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdminHomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdminHomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdminHomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            //new AdminHomeWindow().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextArea Register_Address_JTextArea;
   private javax.swing.JTextField Register_FullName_JTextField;
   private javax.swing.JTextField Register_Password_JTextField;
   private javax.swing.JLabel Register_RegisterUID_JLabel;
   private javax.swing.JButton Register_Registerbtn_JButton;
   private javax.swing.JRadioButton Register_TypeDoctor_JRadioBtn;
   private javax.swing.JRadioButton Register_TypeSecretary_JRadioBtn;
   private javax.swing.JLabel RegisteredUser_UID_JTextField;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
